//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RPG.Class.Item;

public class Animal : Inumano
{
    public Animal()
    {
        this.Nome = "Animal";
        this.PontosdeVida = 3200;
        this.PontosdeMana = 30;
        this.ForcaFisica = 80;
        this.ForcaMagica = 20;
        this.PontoAmrmadura = 90;
        this.ResistenciaMagica = 20;
        this.Agilidade = 50;
        this.NomeImegem = "FtoAnimal.jpg";
        VetItem[0] = new Bio();
        VetItem[1] = new GarraLetal();

        this.MenorArma();
    }

}

